version: "3.1"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            # - 3306:3306
            - 3307:3307
        environment:
            MYSQL_ROOT_PASSWORD: root 
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    # api: 
    #     build: ./backend
    #     volumes: 
    #         - ./backend:/app
    #     command: ./apiStart.sh
    #     ports: 
    #         - 4000:4000

