version: "3.1"

services:
    db:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
    adminer: #tool for DB management
        image: adminer
        restart: always
        ports:
            - 8080:8080
    api:
        build: ./backend
        volumes:
            - ./backend:/app
        command: ./start.sh
        ports:
            - 4000:4000
    # frontend:
    #     build: ./frontend
    #     volumes:
    #         - ./frontend:/app
    #     command: ./start.sh
    #     ports:
    #         - 3000:3000
    #         - 3001:3001